LandonHotel/Models/BookingSuccessViewModel.cs
namespace LandonHotel.Models
{
    public class BookingSuccessViewModel
    {
        public decimal Price { get; set; }
    }
}

LandonHotel/Models/BookingViewModel.cs
using System;
using System.Collections.Generic;
using LandonHotel.Data;

namespace LandonHotel.Models
{
    public class BookingViewModel
    {
        public int RoomId { get; set; }
        public string EmailAddress { get; set; }
        public DateTime CheckOutDate { get; set; }
        public DateTime CheckInDate { get; set; }
        public IList<Room> Rooms { get; set; }
        public string CouponCode { get; set; }
    }
}

LandonHotel/Controllers/BookingController.cs
using System;
using LandonHotel.Data;
using LandonHotel.Models;
using LandonHotel.Services;
using Microsoft.AspNetCore.Mvc;

namespace LandonHotel.Controllers
{
    public class BookingController : Controller
    {
        private readonly IRoomService roomService;
        private readonly IBookingService bookingService;

        public BookingController(IRoomService roomService, IBookingService bookingService)
        {
            this.roomService = roomService;
            this.bookingService = bookingService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = new BookingViewModel()
            {
                CheckInDate = DateTime.Now,
                CheckOutDate = DateTime.Now.AddDays(1),
                Rooms = roomService.GetAllRooms()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(BookingViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Rooms = roomService.GetAllRooms();
                ViewBag.ErrorMessage = "Booking was not valid";

                return View("Index", model);
            }

            var booking = new Booking()
            {
                CheckInDate = model.CheckInDate,
                CheckOutDate = model.CheckOutDate,
                RoomId = model.RoomId,
                CouponCode = model.CouponCode
            };

            return View("Success",
                new BookingSuccessViewModel
                {
                    Price = bookingService.CalculateBookingPrice(booking)
                });

        }
    }
}

LandonHotel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LandonHotel.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

LandonHotel/Views/Booking/Index.cshtml
@model LandonHotel.Models.BookingViewModel
@{
    ViewData["Title"] = "Book Now";
    Html.Html5DateRenderingMode = Html5DateRenderingMode.Rfc3339;
}

<div class="scene" id="welcome">
    <article class="content">
        <div class="gallery">
            <img src="/images/hotel/intro_room.jpg" alt="Intro Gallery Room Sample Pictures">
            <img src="/images/hotel/intro_pool.jpg" alt="Intro Gallery Pool Sample Pictures">
            <img src="/images/hotel/intro_dining.jpg" alt="Intro Gallery Dining Sample Pictures">
            <img src="/images/hotel/intro_attractions.jpg" alt="Intro Gallery Attractions Sample Pictures">
            <img class="hidesm" src="/images/hotel/intro_wedding.jpg" alt="Intro Gallery Dining Sample Pictures">
        </div>
        <h1>Welcome to the Landon&nbsp;Hotel</h1>
    </article>
</div><!-- welcome -->
<form action="/Booking" method="post">
    <div class="scene" id="hotelinfo">
        <article class="heading">
            <h1>Stay With Us</h1>
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert">
                    @ViewBag.ErrorMessage
                </div>
            }
        </article>
        <article id="usefulinfo">
            <section id="arrivalinfo">
                <h2>Your Stay</h2>
                <ul>
                    <li><strong>Email</strong> @Html.TextBoxFor(t=>t.EmailAddress)</li>
                    <li><strong>Check-in</strong> <input type="date" name="@nameof(Model.CheckInDate)" value="@Model.CheckInDate.ToString("yyyy-MM-dd")"/></li>
                    <li><strong>Check-out</strong> <input type="date" name="@nameof(Model.CheckOutDate)" value="@Model.CheckOutDate.ToString("yyyy-MM-dd")"/></li>
                    <li><strong>Coupon Code</strong> @Html.TextBoxFor(m => m.CouponCode)</li>
                </ul>
            </section>
            <section class="checklist" id="services">
                <h2>Choose Room</h2>
                <dl>
                    @foreach (var room in Model.Rooms)
                    {
                        <dd>
                            <label>
                                @Html.RadioButtonFor(r => r.RoomId, room.Id)
                                @room.Name
                            </label>
                        </dd>
                    }
                </dl>
            </section>
            <section id="actions">
                <h2>Ready?</h2>
                <button type="submit">Book Now</button>
            </section>
        </article>
    </div><!-- hotelinfo -->
</form>

LandonHotel/Views/Booking/Success.cshtml
@model LandonHotel.Models.BookingSuccessViewModel
@{
    ViewData["Title"] = "Book Now";
    Html.Html5DateRenderingMode = Html5DateRenderingMode.Rfc3339;
}

<div class="scene" id="welcome">
    <article class="content">
        <div class="gallery">
            <img src="/images/hotel/intro_room.jpg" alt="Intro Gallery Room Sample Pictures">
            <img src="/images/hotel/intro_pool.jpg" alt="Intro Gallery Pool Sample Pictures">
            <img src="/images/hotel/intro_dining.jpg" alt="Intro Gallery Dining Sample Pictures">
            <img src="/images/hotel/intro_attractions.jpg" alt="Intro Gallery Attractions Sample Pictures">
            <img class="hidesm" src="/images/hotel/intro_wedding.jpg" alt="Intro Gallery Dining Sample Pictures">
        </div>
        <h1>Your booking was successful</h1>
        <sub>Estimated Total: $@Model.Price.ToString("0.00")</sub><br />
        <sub>See you soon</sub>
    </article>
</div>

LandonHotel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="scene" id="welcome">
    <article class="content">
        <div class="gallery">
            <img src="/images/hotel/intro_room.jpg" alt="Intro Gallery Room Sample Pictures">
            <img src="/images/hotel/intro_pool.jpg" alt="Intro Gallery Pool Sample Pictures">
            <img src="/images/hotel/intro_dining.jpg" alt="Intro Gallery Dining Sample Pictures">
            <img src="/images/hotel/intro_attractions.jpg" alt="Intro Gallery Attractions Sample Pictures">
            <img class="hidesm" src="/images/hotel/intro_wedding.jpg" alt="Intro Gallery Dining Sample Pictures">
        </div>
        <h1>Welcome to the Landon&nbsp;Hotel</h1>
        <p>
            The original Landon perseveres after 50 years in the heart of West London. The West End neighborhood has something for everyone—from theater to dining to historic sights. And the not-to-miss Rooftop Cafe is a great place for travelers and locals to engage over drinks, food, and good&nbsp;conversation. &nbsp;To learn more about the Landon Hotel in the West End, browse our website and <a href="files/landon_information_sheet_London.pdf">download our handy information sheet</a>.
        </p>
    </article>
</div><!-- welcome -->
<div class="scene" id="hotelinfo">
    <article class="heading">
        <h1>Essential Info</h1>
    </article>
    <article id="usefulinfo">
        <section id="arrivalinfo">
            <h2>Arrival Information</h2>
            <ul>
                <li><strong>Check-in:</strong> 3:00 PM</li>
                <li><strong>Check-out:</strong> 11:00 AM</li>
                <li><strong>Parking:</strong> Self-parking in the underground garage is ￡15 per day and valet-parking is ￡50 per day.</li>
                <li><strong>Airport Shuttle:</strong> Our complimentary airport shuttles leave every hour on the hour, and make trips to Heathrow and Gatwick airports.</li>
                <li><strong>Trains:</strong> The nearest Underground station is at Leicester Square.</li>
                <li><strong>Pet Policy:</strong> Pets of all sizes and types are allowed in designated pet rooms, and the specified common areas. Service animals are allowed everywhere.</li>
            </ul>
        </section>
        <section class="checklist" id="services">
            <h2>Services and Amenities</h2>
            <p>Our services and amenities are designed to make your travel easy, your stay comfortable, and your experience one-of-a-kind.</p>
            <ul>
                <li>Indoor pool</li>
                <li>24-hour fitness center</li>
                <li>Massage therapy</li>
                <li>Full service spa</li>
                <li>In-room jacuzzi tubs</li>
                <li>Rooftop café &amp; smoothie bar</li>
                <li>Coffee bar &amp; pastry shop</li>
                <li>Traditional continental breakfast</li>
                <li>24-hour concierge service</li>
                <li>Business center</li>
                <li>Complimentary wireless service</li>
                <li>Laundry &amp; dry cleaning service</li>
                <li>Daily paper</li>
                <li>Certified "green" hotel</li>
                <li>Pet-friendly rooms &amp; common areas</li>
            </ul>
        </section>
        <section class="checklist" id="accessibility">
            <h2>Accessibility</h2>
            <p>We're committed to maintaining the same quality of service for every individual. We offer the following facilities for those with special needs:</p>
            <ul>
                <li>Grab bars on tub walls</li>
                <li>Shower chairs</li>
                <li>Hand held shower sprayers</li>
                <li>Higher toilets &amp; toilet modifiers</li>
                <li>Lower sink faucet handles</li>
                <li>Wheelchair clearance under sinks &amp; vanity</li>
                <li>Lower racks in closet</li>
                <li>TDD machines</li>
                <li>Telephone light signalers &amp; smoke alarms</li>
                <li>Telephone amplification handsets</li>
                <li>Closed captioned television converters</li>
                <li>Vibrating alarm clocks</li>
                <li>Telephones with volume control</li>
            </ul>
        </section>
    </article>
    <article id="greenprogram">
        <h2>Landon Green Program</h2>
        <p>
            <strong>The Landon Hotel - London</strong> was recently renovated, and we considered the impact on the earth the entire way. From green building materials, to solar power, to energy-friendly lighting and appliances throughout the hotel - we’re saving energy in every socket, outlet, and switch. We’ve also initiated a recycling and composting program that reduces the load to local landfills, while providing valuable raw material for use in new products, or in the case of compost, for use in local gardens and landscapes.
        </p>
    </article>
</div><!-- hotelinfo -->
<div class="scene" id="rooms">
    <header>
        <h1>Guest Rooms</h1>
        <p>Our guest rooms feature sumptuous classic furnishings that evoke visions of London’s rich and long-standing tradition of royalty. While our rooms are decked out in classic design, they each have a modern flair, and contain all the modern comforts expected in today’s luxury hotels. We’ve named our rooms for the notable public squares and circuses around which the West End is laid&nbsp;out.</p>
    </header>
    <article class="room fullheight" id="piccadilly">
        <section class="content">
            <h1>Piccadilly</h1>
            <p>Designed to be our economy room, for those who will be spending more time seeing the sights, and less time hitting the hay. The Piccadilly room has a smaller footprint, but maintains the accommodations of some of our more deluxe rooms.</p>
        </section>
    </article>
    <article class="room fullheight" id="cambridge">
        <section class="content">
            <h1>Cambridge</h1>
            <p>This room features a king bed, with a Comfort-Plus mattress, covered in 400-thread Egyptian cotton sheets. The Cambridge room is decorated in tasteful and warm muted tones, that are soothing on the eyes and senses.</p>
        </section>
    </article>
    <article class="room fullheight" id="westminster">
        <section class="content">
            <h1>Westminster</h1>
            <p>This room is available with a king or two double beds, and is furnished with our Premiere London collection – the softest and most luxurious bed and bath linens.</p>
        </section>
    </article>
    <article class="room fullheight" id="oxford">
        <section class="content">
            <h1>Oxford</h1>
            <p>Our Oxford suites are some of the prettiest and most romantic rooms around and are perfect for honeymoons. All of these feature canopy beds, lots of windows, and spare no modern comfort or convenience, including a TLX media system.</p>
        </section>
    </article>
    <article class="room fullheight" id="victoria">
        <section class="content">
            <h1>Victoria</h1>
            <p>Traveling with the family? Our spacious Victoria suites, with breathtaking views of the city, are the perfect choice. These corner rooms are furnished with a king or two double beds, and have a sofa with a comfortable pullout bed.</p>
        </section>
    </article>
    <article class="room fullheight" id="manchester">
        <section class="content">
            <h1>Manchester</h1>
            <p>The Manchester Executive Suite, is popular with business travelers the world over. These two-room suites feature a king-size bed, living room with leather recliner, full-sized executive desk, and leather desk chair.</p>
        </section>
    </article>
</div><!-- rooms -->
<div class="scene" id="dining">
    <article id="areadining">
        <h1>Dining in the Area</h1>
        <p>The West End is a foodie’s paradise, and the Landon Hotel is in the center of it all. With options for traditional English, Italian, Indian, American, Chinese, and French cuisines, all within two blocks of the hotel, and a variety of tasty culinary delights from many other countries, within a half-mile radius, the only trouble you’ll have is choosing! </p>
    </article>
    <article id="inhotel">
        <section id="rooftopcafe">
            <h2>Rooftop Caf&eacute;</h2>
            <img src="/images/hotel/dining_rooftop.jpg" alt="Dining">
            <p>Landon Rooftop Caf&eacute; is the destination for five star dining. Our master chefs are trained to meet special dietary needs, and we offer a range of vegetarian/vegan, kosher, gluten, and dairy free selections to accommodate our guests. Whether you&rsquo;re in the mood for our award winning roast beef, fresh select salads, appetizing lunch entrees, or delectable desserts, we have you covered.</p>
        </section>

        <section id="smoothiebar">
            <h2>Smoothie Bar</h2>
            <img src="/images/hotel/dining_smoothiebar.jpg" alt="Dining">
            <p>The Rooftop Smoothie Bar gives you panoramic views of the city, where you can have one of our specialty smoothies while you wait for your table. Our top mixologists are constantly bringing new and unique offerings to our smoothie menu. We have a wide range of locally grown, fresh fruit and vegetable choices to make you custom blended drinks. We also have seasonal selections that you won’t find anywhere else.</p>
        </section>

        <section id="coffeebar">
            <h2>Breakfast &amp; Coffee Bar</h2>
            <img src="/images/hotel/dining_lattes.jpg" alt="Dining">
            <p>Our traditional breakfast and coffee bar, located adjacent to our lounge, are the perfect way to start your morning. We offer a wide selection of seasonal fresh fruit, a variety of cereals, croissants, crusty sourdough bread, cook-to-order eggs and omelettes, fresh juice, coffee, and teas. Breakfast is served from 7:00 am to 10:00 am daily. Our coffee bar is open until 6:30 pm daily.</p>
        </section>
    </article><!-- inhotel -->
    <article id="roomservice">
        <h1>Room Service</h1>
        <p>If you’d rather stay in your room and enjoy a quiet evening in, or a relaxing breakfast in bed, room service options are available for all of our dining choices.</p>
    </article>
</div><!-- dining -->
<div class="scene fullheight" id="attractions">
    <article class="content">
        <h1>Local Attractions</h1>
        <p>Whether you’re a theater enthusiast, enjoy epic shopping, or love to stroll and people watch, London’s West End has an endless opportunity to partake. The heart of London’s "Theatreland" offering the best in drama, comedy, and musical productions.</p>
    </article>
</div><!-- attractions -->

@section Hero {
    <article class="fullheight">
        <div class="hgroup">
            <h1>Landon Hotel</h1>
            <h2>West London</h2>
            <p><a href="#welcome"><img src="/images/misc/arrow.png" alt="down arrow"></a></p>
        </div>
    </article>
}

LandonHotel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LandonHotel</title>
    <link rel="icon"
          type="image/png"
          href="/favicon.png">

    <environment names="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header id="intro">
        @RenderSection("Hero", false)

        <nav id="nav">
            <div class="navbar">
                <div class="brand"><a asp-area="" asp-controller="Home" asp-action="Index" asp-fragment="welcome">Landon <span>Hotel</span></a></div>
                <ul>
                    <li><a class="icon info" asp-controller="Home" asp-action="Index" asp-fragment="hotelinfo"><span>info</span></a></li>
                    <li><a class="icon rooms" asp-controller="Home" asp-action="Index" asp-fragment="rooms"><span>rooms</span></a></li>
                    <li><a class="icon dining" asp-controller="Home" asp-action="Index" asp-fragment="dining"><span>dining</span></a></li>
                    <li><a class="icon attractions" asp-controller="Home" asp-action="Index" asp-fragment="attractions"><span>attractions</span></a></li>
                    <li><a class="icon events" asp-controller="Booking" asp-action="Index"><span>book now!</span></a></li>

                </ul>
            </div><!-- navbar -->
        </nav>
    </header>
    <main id="wrapper">

        @RenderBody()
    </main>
    <footer class="scene">
        <article class="content">
            <div id="socialmedia">
                <ul class="group">
                    <li><a href="https://twitter.com"><img class="icon" src="/images/socialmedia/twitter.png" alt="icon for twitter" /></a></li>
                    <li><a href="http://www.facebook.com"><img class="icon" src="/images/socialmedia/facebook.png" alt="icon for facebook" /></a></li>
                    <li><a href="http://www.youtube.com"><img class="icon" src="/images/socialmedia/youtube.png" alt="icon for youtube" /></a></li>
                </ul>
            </div>
        </article>
    </footer>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)

</body>
</html>